### ISSUE TITLE
Bugs with selected menu

### ISSUE THREAD

**Issue by hjwebb01** [CS322-SP23/MixMaster#12]
Ive been working on the selected menu for a couple hours now and everything I have tried to do is not working. 
I have gotten to the point where the text does show up on screen but now I have the issue of being able to remove it and I cant seem to make anymore progress. If anyone can see anything just let me know. All of the code relevant is in the JS file and I gave some basic commenting but reach out if anything is confusing.

**Comment by Archaversine** [comment]
You are attempting to remove something that doesn't exist, on lines 32-35 of your code:

```js
let listContainer = document.getElementById('selected-container');
let listItm = document.createElement('li');
listItm.innerText = item.innerText;
listContainer.removeChild(listItm);
```

The reason you cannot remove `listItm` from `listContainer` is because right before that line you create `listItm` with `document.createElement()`. Since you are just creating it, it is not a child of `listContainer`.

You can iterate through a list of all the children in the `selected-container` div with the following for loop:

```js
let listContainer = document.getElementById('selected-container')
for (let child of listContainer.children)
{
    // Check if child matches
    if (child.innerText === "DrinkNameGoesHere")  listContainer.removeChild(child);
}
```
