### ISSUE TITLE
Basic overview of interaction between database, user input, and app's display

### ISSUE THREAD

**Issue by ejshakman** [CS322-SP23/MixMaster#31]
Can you please explain what lines 38 and down in app.py do, excluding the
`if __name__ == '__main__':`
function?

Not line through line, as your comments do a good job of that (thank you), but just a basic overview of how it works?

**Comment by Archaversine** [comment]
The `get_drinks` route is only called by a POST request which is a type of request that is used to send data to the server (in our case `app.py`). This function then uses the data sent by the post request in combination with the `is_valid_drink` function to search for drinks in the firebase realtime database. It then returns a JSON object back to the client with the information of which drinks matched.

The `cocktail_api_request` function does not work as of now due to the lack of an API key, but essentially combines the necessary RapidAPI HTTP headers with parameters specified by us to retrieve information from RapidAPI. Right now the function returns nothing and simply prints the response sent from RapidAPI.
